---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: Node
    box: bento/centos-7.4
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: rhel7
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
